### ISSUE TITLE
The dependency keys supplied in the cuppa.run() are ignored

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#20]
The keys in the the dependencies dictionary that is passed in the cuppa.run() are not used.

Example below: the QWERTYUIOP dependency is passed with an empty key. In fact you can put any value for the key (blank or otherwise) and it does not matter.
```
import cuppa

class QWERTYUIOP( cuppa.location_dependency( 'ASDFGHJKL' ) ):
  def __call__( self, env, toolchain, variant ):
    super( QWERTYUIOP, self ).__call__( env, toolchain, variant )
    env.AppendUnique( CPPDEFINES = ['IMPORTANT_THING'] )

cuppa.run(
  dependencies = {
    '' : QWERTYUIOP,
  },
  default_options = {
    'ASDFGHJKL-location' : '/tmp',
  },
  default_dependencies = [
    'ASDFGHJKL',
  ],
)
```

This is very confusing when trying to learn how to write a dependency. 

Example project is attached, [dependencyExample.zip](https://github.com/ja11sop/cuppa/files/1115673/dependencyExample.zip)

**Comment by ja11sop** [comment]
It turns out this works for me, but really it shouldn't. Having said that what you are trying to achieve is better suited to using a `profile`. I'll update the documentation to talk about profiles and be more explicit about how to use dependencies. Also I'll take the chance to unify the code used for dependencies and profiles that should make them simpler to use.

**Comment by feedhandler** [comment]
Thanks. 
You're right, in this example a Profile would be more suitable than a Dependency. However it's a contrived scenario which I specifically designed to highlight the issue with the dependencies dictionary, not a real example. The issue with the dependencies dictionary happens in our real project where we have a genuine need for a dependency object.
But anyway, more documentation would be very welcome, thanks. Same for any code changes that make it easier to use.
