### ISSUE TITLE
Tar builder is broken

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#22]
The tar builder seems to be broken
SConscript is like this
```
Import('env')
env.Tar('src.tar', 'src')
```
I get this error:
```
scons: Building targets ...
scons: building associated VariantDir targets: _build/config/gcc62/dbg/x86_64/c++1z/working
scons: `config' is up to date.
tar -c -f _build/config/gcc62/dbg/x86_64/c++1z/working/src.tar _build/config/gcc62/dbg/x86_64/c++1z/working/src
 = Error 1 = 
tar: _build/config/gcc62/dbg/x86_64/c++1z/working/src: Cannot stat: No such file or directory

tar: Exiting with failure status due to previous errors
 === Process Terminated with status 2 (Elapsed 0.019791841507s) === 
 === Errors 1 === 
scons: *** [_build/config/gcc62/dbg/x86_64/c++1z/working/src.tar] Error 2
scons: building terminated because of errors.
```

**Comment by feedhandler** [comment]
Same problem seems to affect a few other builders, e.g. Zip(), Package()

**Comment by ja11sop** [comment]
This error arises because by default SCons doesn't use variant builds but by default Cuppa does. What that means is that you need to explicitly tell SCons where your `src` directory is so this would (for example) work in Cuppa:

```python
Import('env')
env.Tar('src.tar', '#src')
```

If `src` was the result of some other action/method then passing it directly would work for example:

```python
Import('env')
src = env.SomeMethod()
env.Tar('src.tar', src)
```

since the result would be variant aware.

**Comment by feedhandler** [comment]
Thanks. You're right the workaround is to use the hash notation but that can get a bit cumbersome when the object is deep in the directory tree. Is there an easy way to get a variant-aware reference to a local directory without using the hash notation? Something like
```python
Import('env')
env.Tar('src.tar', env.getVariant('src'))
```
Or if there isn't an existing way, could you add one?

**Comment by feedhandler** [comment]
OK don't worry,  found a way to do it
```python
env.Tar(src.tar', Dir('src').srcnode())
```

**Comment by ja11sop** [comment]
That's good solution. Will close this for now but I'll open a new issue to improve the documentation to highlight the fact that with Cuppa you are always using variant builds and so should write your sconscript files accordingly.
