### ISSUE TITLE
Random build failures when using --parallel

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#30]
Builds randomly fail when I use --parallel.
After a failure, if I immediately rebuild, it works OK.

Attached [build.txt](https://github.com/ja11sop/cuppa/files/1260778/build.txt) file shows the build output

**Comment by ja11sop** [comment]
Please check the latest commit of cuppa. There is an issue with executing multiple invocations of bjam itself in parallel which can cause spurious failures. This should be addressed in the latest code on master.

**Comment by ja11sop** [comment]
Fixed with this commit 5434172
