### ISSUE TITLE
Enhancement request: add "build identifier" argument to env.CreateVersion()

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#31]
It would be cool if env.CreateVersion() took an extra argument that could represent a kind of build identifier (e.g. Jenkins job ID, or gitlab pipeline number). This would be available as 
```
    static const char*              build_id();
```
in the build::identity class, and show as "ID" in the Build section of build::identity::report()
```
Product:
  |- Version    = 00.01.04-manual
  |- Repository = git@server:project.git
  |- Branch     = master
  +- Revision   = 87775cb
Build:
  |- Variant    = rel
  |- Time       = 2017-10-18 11:06:36.802951
  |- User       = me
  |- Host       = qwerty
  +- ID         = 3214 <<<<<<<<<<<<<< available here
Dependencies:
 boost
  |- Version    = 1_64
  |- Repository =
  ...
```

**Comment by ja11sop** [comment]
Added this as a string - if no build id is specified the build id is reported as "None". Closing this issue. Please request for it to be re-opened if this change does not meet your needs.
