### ISSUE TITLE
cuppa pulls wrong git branch if default branch is not "master"

### ISSUE THREAD

**Issue by feedhandler** [ja11sop/cuppa#36]
We have a git repo which is used as a location dependency in cuppa
The default branch of the repo is not "master", it's "develop"
The branch name is not specified in the location dependency in the SConstruct
cuppa correctly clones the repo with the default branch (develop) in the initial build 
In subsequent builds, cuppa pulls from the master branch and the build fails.

SConstruct:
```
    default_options = {
      'Config-location'  : 'git+http://my.server/Core-services/Core.git',
      'Config-include'   : 'Config/include',
    },
  dependencies = [
      cuppa.location_dependency( 'Config' ),
  ],
```

First build, it clones and checkout the "develop" branch (correct)
```
cuppa: location: __init__:430 [debug] Using [git+http://my.server/Core-services/Core.git] at [develop rev. f4309f6] stored in [/home/dmsdev/repo/Darwin/_cuppa/git_http_my.server__Core-services_Core.git]
```
Subsequent builds, it pulls from origin/master and the build breaks
```
cuppa: location: get_local_directory:289 [debug] Updating [git+http://my.server/Core-services/Core.git] in [/home/dmsdev/repo/Darwin/_cuppa/git_http_my.server__Core-services_Core.git/] on ['origin/master'] at [develop rev. f4309f6]
```
i think the bug is in location.py:
```
    def get_rev_options( self, vc_type, vcs_backend ):
        url, rev = vcs_backend.get_url_rev()
        if vc_type == 'git':
            if rev:
                return [rev]
            else:
                return ['origin/master'] /////////////// this is where the problem comes from
```
I'm not sure exactly how to fix the code, but it needs to to get the branch name by looking at the local repo (or something similar...) instead of assuming it's master branch.

Workaround is to explicitly specify the branch name in the location field, e.g.
```
      'Config-location'  : 'git+http://ldnpbldjen01.eur.ad.tullib.com/Core-services/Core.git@develop',
```

**Comment by ja11sop** [comment]
Can you check if the referenced commit partially or fully resolves this issue?

**Comment by feedhandler** [comment]
Yep, seems to be fixed now. Thanks
