### ISSUE TITLE
Python3: pip install fails with 'no module named 'urlparse'

### ISSUE THREAD

**Issue by pauschar** [ja11sop/cuppa#46]
Hi, 
I have a WinPython3 (3.7.1). Pip-installing 'cuppa' gives 
 ModuleNotFoundError: No module named 'urlparse'

A quick search tells me that 'urlparse' is deprecated/not available any longer in Py3. Does this mean that cuppa requires Py2?

Thx for any hint ...

**Comment by ja11sop** [comment]
Python 3 support still a WIP with `pip` changes also complicating this but expect resolution in the next few days.
