### ISSUE TITLE
scons 4.1.0 compatibility

### ISSUE THREAD

**Issue by pwj58** [ja11sop/cuppa#67]
The following error with scons 4.1.0.post1 installed. 

cuppa --dbg
scons: Reading SConscript files ...
cuppa: __init__: [critical] Cuppa terminated by exception [ImportError: cannot import name 'cached_get_installed_vcs' from 'SCons.Tool.MSCommon.vc' (/home/x/.local/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py)]
cuppa: __init__: [warn] Use --verbosity=exception (or above) to see the stack
scons: *** cannot import name 'cached_get_installed_vcs' from 'SCons.Tool.MSCommon.vc' (/home/x/.local/lib/python3.9/site-packages/SCons/Tool/MSCommon/vc.py)  Stop.

see https://github.com/SCons/scons/commit/07c091119fc56bc455133060bfbceda36debfb95#diff-21573f031c94392d25fc95a269a0d6674992c4731444e31237b705b88db79dbd

**Comment by ja11sop** [comment]
Closed by https://github.com/ja11sop/cuppa/pull/68
